name: 'Setup GraalVM environment'
description: 'Setup your runner with GraalVM built by Gluon'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  graalvm:
    description: 'The GraalVM version built by Gluon, defaults to latest'
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
