name: Simple example of using

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GraalVM
        uses: gluonhq/setup-graalvm@master

      - name: Check java binary
        run: java -version

      - name: Check gu binary
        run: gu install native-image

  simple:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gu-binary: [gu, gu.cmd]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: macos-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu
    steps:
      - name: Setup GraalVM
        uses: gluonhq/setup-graalvm@master

      - name: Check java binary
        run: java -version

      - name: Check gu binary
        run: |
          ${{ matrix.gu-binary }} install native-image
